-- MySQL Script generated by MySQL Workbench
-- Thu Mar  6 10:52:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  avto  DEFAULT CHARACTER SET utf8 ;
USE  avto  ;

-- -----------------------------------------------------
-- Table   znamka 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   znamka  ;

CREATE TABLE IF NOT EXISTS   znamka  (
   idZnamka  INT NOT NULL AUTO_INCREMENT,
   ime  VARCHAR(45) NOT NULL,
  PRIMARY KEY ( idZnamka ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table   model 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   model  ;

CREATE TABLE IF NOT EXISTS   model  (
   idModel  INT NOT NULL AUTO_INCREMENT,
   ime  VARCHAR(45) NOT NULL,
   znamka_idZnamka  INT NOT NULL,
  PRIMARY KEY ( idModel ,  znamka_idZnamka ),
  CONSTRAINT  fk_model_znamka 
    FOREIGN KEY ( znamka_idZnamka )
    REFERENCES   znamka  ( idZnamka )
    on delete restrict
    on update cascade)
ENGINE = InnoDB;

CREATE INDEX  fk_model_znamka_idx  ON   model  ( znamka_idZnamka  ASC) VISIBLE;


-- -----------------------------------------------------
-- Table   gorivo 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   gorivo  ;

CREATE TABLE IF NOT EXISTS   gorivo  (
   idGorivo  INT NOT NULL AUTO_INCREMENT,
   ime  VARCHAR(45) NOT NULL,
  PRIMARY KEY ( idGorivo ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table   vrata 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   vrata  ;

CREATE TABLE IF NOT EXISTS   vrata  (
   idVrata  INT NOT NULL AUTO_INCREMENT,
   kolicina  INT NOT NULL,
  PRIMARY KEY ( idVrata ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table   menjalnik 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   menjalnik  ;

CREATE TABLE IF NOT EXISTS   menjalnik  (
   idMenjalnik  INT NOT NULL AUTO_INCREMENT,
   vrsta  VARCHAR(45) NOT NULL,
  PRIMARY KEY ( idMenjalnik ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table   geslo 
-- -----------------------------------------------------
DROP TABLE IF EXISTS geslo ;

CREATE TABLE IF NOT EXISTS geslo (
  `idGeslo` INT NOT NULL AUTO_INCREMENT,
  `geslo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `uporabnik_idUporabnik` INT NOT NULL,
  PRIMARY KEY (`idGeslo`, `uporabnik_idUporabnik`),
  CONSTRAINT `fk_geslo_uporabnik1`
    FOREIGN KEY (`uporabnik_idUporabnik`)
    REFERENCES uporabnik (`idUporabnik`)
    on delete restrict
    on update cascade)
ENGINE = InnoDB;

CREATE INDEX `fk_geslo_uporabnik1_idx` ON geslo (`uporabnik_idUporabnik` ASC) VISIBLE;



-- -----------------------------------------------------
-- Table   uporabnik 
-- -----------------------------------------------------
DROP TABLE IF EXISTS uporabnik ;

CREATE TABLE IF NOT EXISTS uporabnik (
  `idUporabnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUporabnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table   avto 
-- -----------------------------------------------------
DROP TABLE IF EXISTS   avto  ;

CREATE TABLE IF NOT EXISTS   avto  (
   idAvto  INT NOT NULL AUTO_INCREMENT,
   letnik  INT NOT NULL,
   kilometri INT NOT NULL,
   cena  FLOAT NOT NULL,
   opis  VARCHAR(10000) NOT NULL,
   pogon4  TINYINT(1) NOT NULL,
   datumObjave  INT NOT NULL,
   model_idModel  INT NOT NULL,
   model_znamka_idZnamka  INT NOT NULL,
   gorivo_idGorivo  INT NOT NULL,
   vrata_idVrata  INT NOT NULL,
   menjalnik_idMenjalnik  INT NOT NULL,
   uporabnik_idUporabnik  INT NOT NULL,
  PRIMARY KEY ( idAvto ,  model_idModel ,  model_znamka_idZnamka ,  gorivo_idGorivo ,  vrata_idVrata ,  menjalnik_idMenjalnik ,  uporabnik_idUporabnik ),
  CONSTRAINT  fk_avto_model1 
    FOREIGN KEY ( model_idModel  ,  model_znamka_idZnamka )
    REFERENCES   model  ( idModel  ,  znamka_idZnamka )
    on delete restrict
    on update cascade,
  CONSTRAINT  fk_avto_gorivo1 
    FOREIGN KEY ( gorivo_idGorivo )
    REFERENCES   gorivo  ( idGorivo )
    on delete restrict
    on update cascade,
  CONSTRAINT  fk_avto_vrata1 
    FOREIGN KEY ( vrata_idVrata )
    REFERENCES   vrata  ( idVrata )
    on delete restrict
    on update cascade,
  CONSTRAINT  fk_avto_menjalnik1 
    FOREIGN KEY ( menjalnik_idMenjalnik )
    REFERENCES   menjalnik  ( idMenjalnik )
    on delete restrict
    on update cascade,
  CONSTRAINT  fk_avto_uporabnik1 
    FOREIGN KEY ( uporabnik_idUporabnik )
    REFERENCES   uporabnik  ( idUporabnik )
    on delete restrict
    on update cascade)
ENGINE = InnoDB;

CREATE INDEX  fk_avto_model1_idx  ON   avto  ( model_idModel  ASC,  model_znamka_idZnamka  ASC) VISIBLE;

CREATE INDEX  fk_avto_gorivo1_idx  ON   avto  ( gorivo_idGorivo  ASC) VISIBLE;

CREATE INDEX  fk_avto_vrata1_idx  ON   avto  ( vrata_idVrata  ASC) VISIBLE;

CREATE INDEX  fk_avto_menjalnik1_idx  ON   avto  ( menjalnik_idMenjalnik  ASC) VISIBLE;

CREATE INDEX  fk_avto_uporabnik1_idx  ON   avto  ( uporabnik_idUporabnik  ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
